### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by gchaincl**
@j-haj I'd love to get some feedback from you.

### CODE REVIEW

**Comment by j-haj** [comment]
@gchaincl I think it looks good! Enforcing the no-duplication of work will need to fall on the shoulders of those who can merge PRs. See [this](https://github.com/rust-lang-nursery/rust-cookbook/issues/287) of how other projects have handled this. The Rust Cookbook doesn't actually specifically state "no duplication of work" but it is strongly implied by the tags (we have a "claimed" tag), and is enforced by those who can merge PRs. Anyways, great work!

**Comment by gchaincl** [comment]
How would you manage the situation where someone's claim an issue and never delivers it?

**Comment by j-haj** [comment]
I think it varies on community but it seems a common approach is to simply add a comment to the issue "@ someone are you still working on this?" if the answer is yes, great, otherwise the "work-in-progress" or "claimed" tag gets removed and the issue is available for others to work on.

**Comment by gchaincl** [comment]
Makes sense

**Pull request merged**
