### PR TITLE
Add snapcraft yaml to enable builds of snaps

### PR DESCRIPTION
**Pull request by popey**
Hello!

This PR adds support for building snaps of httplab via snapcraft - see http://snapcraft.io/ for more information. Hooking this up means that builds of master can be pushed to the store and make latest builds of httplab are immediately available to millions of users. 

To test the build used to make the snap, on an up to date 16.04 machine

apt install snapcraft

git clone http://github.com/popey/httplab
git checkout add-snapcraft
cd httplab
snapcraft

This will build a snap which can be installed via:-

snap install httplab_0.1.0+git_amd64.snap --dangerous

(the --dangerous is required as it's an unsigned package being side-loaded, rather than a signed one from the store).

Test the application as expected.

Would be great to get this merged, and then hook up the automated builds to land in the store directly, as per http://snapcraft.io/docs/build-snaps/ci-integration. Happy to help through that process. We also have an automated system at http://build.snapcraft.io/ which could be used to auto-build and push to the store.

Once published in the store, it can be installed with:-

snap install httplab --edge

Later, when pushed to the stable store, it can be installed with:-

snap insatll httplab

### CODE REVIEW

**Comment by gchaincl** [comment]
Never heard from snapcraft before, looks very interesting. Would it be possible to move `./snap` to `./contrib/snap`?

**Comment by popey** [comment]
Thanks for the fast response. snapcraft looks for the yaml in the current directory or ./snap by default. However, if you move snap/snapcraft under contrib, and run it from there, it will work, so long as the "source:" line is changed thus:-

source: ../../

**Comment by gchaincl** [comment]
I think ./span should do the job then, like the travis file

**Comment by gchaincl** [comment]
@popey any progress on this?

**Comment by popey** [comment]
Apologies for the delay. I've moved the snapcraft.yaml to contrib/snap as requested. So now you should be able to run "snapcraft" from inside contrib/snap and it will build a .snap for you.

**Comment by gchaincl** [comment]
Cool, thanks!

**Pull request merged**
