### PR TITLE
Add ability to save a request to file, closes #26

### LINKED ISSUE #26: Form POST hard to view
The body of form POST requests is very hard to read due to there being no word wrapping and home/end buttons not working, see:

screenshot from 2017-04-20 11-24-26

### PR DESCRIPTION
**Pull request by gchaincl**
<kbd>Ctrl+f</kbd> saves the current request into a file, @swordbeta, please take a look.

### CODE REVIEW

**Comment by swordbeta** [comment]
Thanks for this! The request is saved, but the escape sequences in the headers as well, is there a way to remove these?

screenshot from 2017-04-21 22-07-28

**Comment by gchaincl** [comment]
good point!, I'll remove them

**Comment by gchaincl** [comment]
@swordbeta dc88542 should fix the problem, can u confirm?

**Comment by gchaincl** [comment]
@swordbeta dc88542 should fix the problem, can u confirm?

**Comment by swordbeta** [comment]
@gchaincl Works great, thanks!

**Pull request merged**
