### PR TITLE
CORS support

### PR DESCRIPTION
**Pull request by gchaincl**
@spemberton this should solve the CORS issue #39. I'd love you to review it.
Thanks in advance!

### CODE REVIEW

**Comment by gchaincl** [comment]
ping @spemberton

**Comment by spemberton** [comment]
I hope to be able to review it this week. On another project right now.

**Comment by gchaincl** [comment]
Thanks @spemberton !

**Comment by spemberton** [comment]
Never used go before, so I need help on how to compile/run this version.

**Comment by gchaincl** [comment]
ok, after installing [go](http://golang.org/dl) type:
```
mkdir -p go/src/github.com/gchaincl && cd $_
git clone https://github.com/gchaincl/httplab.git
cd httplab
git checkout cors
go get ./...
go run ./cmd/httplab/main.go
```

**Comment by spemberton** [comment]
And what should GOPATH be set to?

**Comment by gchaincl** [comment]
export GOPATH=$HOME/go

**Comment by gchaincl** [comment]
but I think if you're running go 1.8/x, `$HOME/go` is assumed

**Comment by spemberton** [comment]
$ go get ./...
go install: no install location for directory  
/home/steven/Downloads/httplab-cors outside GOPATH

**Comment by gchaincl** [comment]
well, your repo (httplab-cors) should live inside `$GOPATH/src/github.com/gchaincl`
Check the instructions above

**Comment by spemberton** [comment]
OK, worked like a charm!
The only thing I would ask is that you keep the CORS requests and responses in the Request History, so that you can page through them to check what happened.
Otherwise, perfect!
Thanks, great work!

**Comment by gchaincl** [comment]
Great, let's do this, I'm merging this so we have something useful, then you can open a new issue with your request, I'll try to implement it for the next release

**Pull request merged**
